# Generated by Django 3.1.3 on 2020-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='', upload_to='post-images'),
            preserve_default=False,
        ),
    ]
