# Generated by Django 3.1.3 on 2020-11-10 07:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201106_1100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-images/default.png', upload_to='profile-images'),
        ),
    ]
